// Example starts a gRPC server on one port and a tiny HTTP /healthz server
// on another. Two ports is the cleanest way to demonstrate gRPC without
// pulling in cmux or TLS for the learning version.
//
// What this file does, end to end:
//
//  1. Define a GreetServiceServer implementation that says "Hello, {name}!".
//  2. Register it on a grpc.Server and start serving on :9000.
//  3. Start a plain net/http server with /healthz on :9001 so curl works.
//
// Run it with:
//
//	go run .
//
// Then in another terminal:
//
//	# Plain HTTP probe (works without any gRPC tooling):
//	curl -i http://localhost:9001/healthz
//
//	# gRPC probe — see the README for grpcurl / raw-client commands.
//	# (grpcurl -plaintext localhost:9000 greet.v1.GreetService/Greet -d '{"name":"world"}')
package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"net/http"

	"google.golang.org/grpc"

	"github.com/kianooshaz/grpc-from-scratch/proto"
)

// ─── The service implementation ─────────────────────────────────────────────
//
// A gRPC service is just a struct whose methods match the interface that
// protoc-gen-go-grpc generated (see proto/greeter_grpc.pb.go). The
// generated interface requires:
//
//   - Greet(ctx, *GreetRequest) (*GreetResponse, error)
//
// All we do is greet the caller. This is the entire "service" — there's no
// router, no middleware, no auth. gRPC is just a typed RPC library; you
// bring the rest.

// GreetServer implements proto.GreetServiceServer.
//
// Embedding proto.UnimplementedGreetServiceServer is the convention
// generated by protoc-gen-go-grpc: it gives you default "Unimplemented"
// errors for methods you haven't written yet, and keeps your struct
// forward-compatible if the .proto file grows new RPCs.
type GreetServer struct {
	proto.UnimplementedGreetServiceServer
}

// Greet is the only RPC declared in greeter.proto. We echo the name back
// with a "Hello, " prefix. This is the smallest meaningful gRPC service
// you can write.
func (s *GreetServer) Greet(_ context.Context, req *proto.GreetRequest) (*proto.GreetResponse, error) {
	return &proto.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.GetName()),
	}, nil
}

func main() {
	// ─── gRPC server on :9000 ──────────────────────────────────────────
	grpcAddr := "localhost:9000"
	grpcLis, err := net.Listen("tcp", grpcAddr)
	if err != nil {
		log.Fatalf("listen %s: %v", grpcAddr, err)
	}
	grpcSrv := grpc.NewServer()
	proto.RegisterGreetServiceServer(grpcSrv, &GreetServer{})
	log.Printf("gRPC listening on %s", grpcAddr)

	go func() {
		if err := grpcSrv.Serve(grpcLis); err != nil {
			log.Fatalf("grpc serve: %v", err)
		}
	}()

	// ─── HTTP /healthz on :9001 ────────────────────────────────────────
	// A plain HTTP endpoint so curl works without any gRPC tooling. This
	// is purely for the learning example — in a real service you'd use
	// one port with h2c (HTTP/2 cleartext) or with TLS, or use cmux to
	// multiplex gRPC and plain HTTP on one socket.
	httpAddr := "localhost:9001"
	httpMux := http.NewServeMux()
	httpMux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})
	log.Printf("HTTP listening on %s (try: curl -i %s/healthz)", httpAddr, httpAddr)

	if err := http.ListenAndServe(httpAddr, httpMux); err != nil {
		log.Fatal(err)
	}
}
